# python:3.10.11의 이미지로 부터
FROM python:3.10.11

# 파이썬 버퍼 사용 해제
ENV PYTHONUNBUFFERED 0

# Author 기입
LABEL maintainer="penkins@thpeach.kr"

# Add User
RUN groupadd -g 1001 fastapiuser
RUN useradd -rm -d /home/fastapiuser -s /bin/bash -g fastapiuser -G sudo -u 1001 fastapiuser
USER fastapiuser
WORKDIR /home/fastapiuser

# 레포지토리 클론
RUN git clone https://github.com/the-peach-drone/fastapi-flight-record-server.git

# 레포지토리로 이동
WORKDIR /fastapi-flight-record-server

# 의존성 패키지 설치
RUN pip3 install -r requirements.txt

# container가 구동되면 실행
ENTRYPOINT [ "gunicorn", "-b", "0.0.0.0:45555", "main:app", "-k", "uvicorn.workers.UvicornWorker" ]